const employees = [
    {
      id: "niranjana@gg.com",
      name: "Niranjana",
      date: "2020-10-03",
      role: "Developer",
      status: "Active",
      address: "Mananthavady",
      experience: "4 years",
      department: "Consulting",
      address:"California",
    },
    {
      name: "Shaheen",
      id: "shaheen@fun.com",
      date: "2021-09-01",
      role: "Software Developer",
      status: "Inactive",
      experience: "2 years",
      department: "Consulting",
      address:"California",
    },
    {
      name: "Alex",
      id: "alex@company.com",
      date: "2020-08-15",
      role: "Project Manager",
      status: "Active",
      experience: "5 years",
      department: "Consulting",
      address:"California",
    },
    {
      name: "Jordan",
      id: "jordan@tech.com",
      date: "2019-04-22",
      role: "UI/UX Designer",
      status: "Active",
      experience: "3 years",
      department: "Consulting",
      address:"California",
    },
    {
      name: "Casey",
      id: "casey@innovate.com",
      date: "2022-01-10",
      role: "Marketing Specialist",
      status: "Probation",
      experience: "1 year",
      department: "Consulting",
      address:"California",
    },
    {
      name: "Morgan",
      id: "morgan@develop.com",
      date: "2018-07-19",
      role: "Backend Developer",
      status: "Probation",
      department: "Consulting",
      experience: "4 years",
      address:"California",
    },
    {
      name: "Jamie",
      id: "jamie@create.com",
      date: "2021-03-03",
      role: "Frontend Developer",
      status: "Active",
      department: "Consulting",
      experience: "2 years",
      address:"California",
    },
    {
      name: "Taylor",
      id: "taylor@solution.com",
      date: "2020-11-12",
      role: "Data Analyst",
      status: "Probation",
      department: "Consulting",
      experience: "2 years",
      address:"California",
    },
    {
      name: "Drew",
      id: "drew@enterprise.com",
      date: "2019-06-08",
      role: "System Administrator",
      status: "Probation",
      department: "Consulting",
      experience: "3 years",
      address:"California",
    },
    {
      name: "Pat",
      id: "pat@network.com",
      date: "2022-02-20",
      role: "Network Engineer",
      status: "Active",
      department: "Consulting",
      experience: "1 year",
      address:"California",
    },
    {
      name: "Jordan",
      id: "jordan@tech.com",
      date: "2019-04-22",
      role: "UI/UX Designer",
      status: "Active",
      department: "Consulting",
      experience: "3 years",
      address:"California",
    },
    {
      name: "Casey",
      id: "casey@innovate.com",
      date: "2022-01-10",
      role: "Marketing Specialist",
      status: "Inactive",
      department: "Consulting",
      experience: "1 year",
      address:"California",
    },
    {
      name: "Morgan",
      id: "morgan@develop.com",
      date: "2018-07-19",
      role: "Backend Developer",
      status: "Active",
      department: "Consulting",
      experience: "4 years",
      address:"California",
    },
    {
      name: "Jamie",
      id: "jamie@create.com",
      date: "2021-03-03",
      role: "Frontend Developer",
      status: "Inactive",
      department: "Consulting",
      experience: "2 years",
      address:"California",
    },
    {
      name: "Sam",
      id: "sam@cloud.com",
      date: "2021-05-16",
      role: "Cloud Solutions Architect",
      status: "Active",
      department: "Consulting",
      experience: "2 years",
      address:"California",
    },
  ];

  export default employees;